// resolves the plain us keymap against real xkb data and regenerates
// src/input/default_keymap.rs. run from the repo:
//   cargo run --manifest-path tools/gen-keymap/Cargo.toml
//
// the compositor parses the embedded text at boot instead of touching
// disk, so a default-keymap session needs no xkb data files installed;
// configured layouts still resolve from disk at runtime. the freshness
// test in the generated file pins this file's hash, so editing here
// without rerunning fails cargo test.
//
// XKB_CONFIG_ROOT must point at xkeyboard-config's data (the dev shell
// sets it).

use kbvm::xkb::diagnostic::{Diagnostic, DiagnosticHandler, DiagnosticKind, Severity};
use kbvm::xkb::rmlvo::Group;
use sha2::{Digest, Sha256};

struct ErrorsOnly;

impl DiagnosticHandler for ErrorsOnly {
    fn filter(&self, kind: DiagnosticKind, _is_fatal: bool) -> bool {
        matches!(kind.severity(), Severity::Error)
    }

    fn handle(&mut self, diag: Diagnostic) {
        eprintln!("gen-keymap: xkb: {}", diag.with_code());
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn main() {
    let root = std::env::var("XKB_CONFIG_ROOT")
        .expect("XKB_CONFIG_ROOT must be set (run inside the dev shell)");
    let mut builder = kbvm::xkb::Context::builder();
    builder.prepend_path(&root);
    let context = builder.build();

    let groups: Vec<Group<'_>> = Group::from_layouts_and_variants("us", "").collect();
    let keymap = context.keymap_from_names(ErrorsOnly, None, None, Some(&groups), None);
    let text = keymap.format().to_string();
    // a resolution against missing data degenerates silently; refuse it
    assert!(
        text.len() > 10_000,
        "resolved keymap is implausibly small ({} bytes) - xkb data missing?",
        text.len()
    );

    // smallest raw-string fence the text cannot terminate early
    let mut fence = String::from("#");
    while text.contains(&format!("\"{fence}")) {
        fence.push('#');
    }

    let gen_hash = hex(&Sha256::digest(include_str!("main.rs").as_bytes()));
    let map_hash = hex(&Sha256::digest(text.as_bytes()));

    let out = format!(
        r"// generated by tools/gen-keymap - DO NOT EDIT. the default keymap
// (plain us), fully resolved so booting needs no xkb data files on
// disk; configured layouts still resolve from disk. to regenerate:
//   cargo run --manifest-path tools/gen-keymap/Cargo.toml
// the test below fails if the generator and this text drift.

pub const DEFAULT_KEYMAP: &str = r{fence}{quote}{text}{quote}{fence};

#[cfg(test)]
mod tests {{
    use sha2::{{Digest, Sha256}};

    // pins tools/gen-keymap/src/main.rs as of the last regeneration
    const GEN_SRC_HASH: &str = {q}{gen_hash}{q};
    const MAP_HASH: &str = {q}{map_hash}{q};
    const REGEN: &str =
        {q}default keymap out of date - rerun: cargo run --manifest-path tools/gen-keymap/Cargo.toml{q};

    fn hex(b: &[u8]) -> String {{
        b.iter().map(|x| format!({q}{{x:02x}}{q})).collect()
    }}

    #[test]
    fn generator_matches_committed_text() {{
        let gen_src = include_str!({q}../../tools/gen-keymap/src/main.rs{q});
        assert_eq!(GEN_SRC_HASH, hex(&Sha256::digest(gen_src.as_bytes())), {q}{{REGEN}}{q});
        assert_eq!(MAP_HASH, hex(&Sha256::digest(super::DEFAULT_KEYMAP.as_bytes())), {q}{{REGEN}}{q});
    }}
}}
",
        quote = '"',
        q = '"',
    );

    std::fs::write("src/input/default_keymap.rs", out).expect("write src/input/default_keymap.rs");
    println!("wrote src/input/default_keymap.rs ({} bytes of keymap)", text.len());
}
