// generated by tools/gen-keymap - DO NOT EDIT. the default keymap
// (plain us), fully resolved so booting needs no xkb data files on
// disk; configured layouts still resolve from disk. to regenerate:
//   cargo run --manifest-path tools/gen-keymap/Cargo.toml
// the test below fails if the generator and this text drift.

pub const DEFAULT_KEYMAP: &str = r#"xkb_keymap {
    xkb_keycodes {
        minimum = 8;
        maximum = 709;

        indicator 1 = "Caps Lock";
        indicator 2 = "Num Lock";
        indicator 3 = "Scroll Lock";
        indicator 4 = "Compose";
        indicator 5 = "Kana";
        indicator 6 = "Sleep";
        indicator 7 = "Suspend";
        indicator 8 = "Mute";
        indicator 9 = "Misc";
        indicator 10 = "Mail";
        indicator 11 = "Charging";
        virtual indicator 12 = "Shift Lock";
        virtual indicator 13 = "Group 2";
        virtual indicator 14 = "Mouse Keys";

        <AB01> = 52;
        <AB02> = 53;
        <AB03> = 54;
        <AB04> = 55;
        <AB05> = 56;
        <AB06> = 57;
        <AB07> = 58;
        <AB08> = 59;
        <AB09> = 60;
        <AB10> = 61;
        <AC01> = 38;
        <AC02> = 39;
        <AC03> = 40;
        <AC04> = 41;
        <AC05> = 42;
        <AC06> = 43;
        <AC07> = 44;
        <AC08> = 45;
        <AC09> = 46;
        <AC10> = 47;
        <AC11> = 48;
        <AD01> = 24;
        <AD02> = 25;
        <AD03> = 26;
        <AD04> = 27;
        <AD05> = 28;
        <AD06> = 29;
        <AD07> = 30;
        <AD08> = 31;
        <AD09> = 32;
        <AD10> = 33;
        <AD11> = 34;
        <AD12> = 35;
        <AE01> = 10;
        <AE02> = 11;
        <AE03> = 12;
        <AE04> = 13;
        <AE05> = 14;
        <AE06> = 15;
        <AE07> = 16;
        <AE08> = 17;
        <AE09> = 18;
        <AE10> = 19;
        <AE11> = 20;
        <AE12> = 21;
        <AGAI> = 137;
        <ALT> = 204;
        <BKSL> = 51;
        <BKSP> = 22;
        <CAPS> = 66;
        <COMP> = 135;
        <COPY> = 141;
        <CUT> = 145;
        <DELE> = 119;
        <DOWN> = 116;
        <END> = 115;
        <ESC> = 9;
        <FIND> = 144;
        <FK01> = 67;
        <FK02> = 68;
        <FK03> = 69;
        <FK04> = 70;
        <FK05> = 71;
        <FK06> = 72;
        <FK07> = 73;
        <FK08> = 74;
        <FK09> = 75;
        <FK10> = 76;
        <FK11> = 95;
        <FK12> = 96;
        <FK13> = 191;
        <FK14> = 192;
        <FK15> = 193;
        <FK16> = 194;
        <FK17> = 195;
        <FK18> = 196;
        <FK19> = 197;
        <FK20> = 198;
        <FK21> = 199;
        <FK22> = 200;
        <FK23> = 201;
        <FK24> = 202;
        <FRNT> = 140;
        <HELP> = 146;
        <HENK> = 100;
        <HIRA> = 99;
        <HJCV> = 131;
        <HKTG> = 101;
        <HNGL> = 130;
        <HOME> = 110;
        <HYPR> = 207;
        <I126> = 126;
        <I128> = 128;
        <I129> = 129;
        <I147> = 147;
        <I148> = 148;
        <I150> = 150;
        <I151> = 151;
        <I152> = 152;
        <I153> = 153;
        <I155> = 155;
        <I156> = 156;
        <I157> = 157;
        <I158> = 158;
        <I159> = 159;
        <I160> = 160;
        <I161> = 161;
        <I162> = 162;
        <I163> = 163;
        <I164> = 164;
        <I165> = 165;
        <I166> = 166;
        <I167> = 167;
        <I169> = 169;
        <I170> = 170;
        <I171> = 171;
        <I172> = 172;
        <I173> = 173;
        <I174> = 174;
        <I175> = 175;
        <I176> = 176;
        <I177> = 177;
        <I179> = 179;
        <I180> = 180;
        <I181> = 181;
        <I182> = 182;
        <I185> = 185;
        <I186> = 186;
        <I187> = 187;
        <I188> = 188;
        <I189> = 189;
        <I190> = 190;
        <I208> = 208;
        <I209> = 209;
        <I210> = 210;
        <I211> = 211;
        <I212> = 212;
        <I213> = 213;
        <I214> = 214;
        <I215> = 215;
        <I216> = 216;
        <I217> = 217;
        <I218> = 218;
        <I220> = 220;
        <I221> = 221;
        <I223> = 223;
        <I224> = 224;
        <I225> = 225;
        <I226> = 226;
        <I227> = 227;
        <I228> = 228;
        <I229> = 229;
        <I231> = 231;
        <I232> = 232;
        <I233> = 233;
        <I234> = 234;
        <I235> = 235;
        <I236> = 236;
        <I237> = 237;
        <I238> = 238;
        <I239> = 239;
        <I240> = 240;
        <I241> = 241;
        <I242> = 242;
        <I243> = 243;
        <I244> = 244;
        <I245> = 245;
        <I246> = 246;
        <I247> = 247;
        <I248> = 248;
        <I249> = 249;
        <I250> = 250;
        <I251> = 251;
        <I252> = 252;
        <I253> = 253;
        <I254> = 254;
        <I255> = 255;
        <I256> = 256;
        <I360> = 360;
        <I361> = 361;
        <I362> = 362;
        <I363> = 363;
        <I365> = 365;
        <I366> = 366;
        <I367> = 367;
        <I368> = 368;
        <I370> = 370;
        <I371> = 371;
        <I372> = 372;
        <I373> = 373;
        <I374> = 374;
        <I376> = 376;
        <I377> = 377;
        <I378> = 378;
        <I379> = 379;
        <I380> = 380;
        <I381> = 381;
        <I382> = 382;
        <I383> = 383;
        <I384> = 384;
        <I385> = 385;
        <I386> = 386;
        <I387> = 387;
        <I388> = 388;
        <I389> = 389;
        <I391> = 391;
        <I392> = 392;
        <I393> = 393;
        <I394> = 394;
        <I395> = 395;
        <I396> = 396;
        <I397> = 397;
        <I398> = 398;
        <I400> = 400;
        <I401> = 401;
        <I404> = 404;
        <I405> = 405;
        <I406> = 406;
        <I407> = 407;
        <I408> = 408;
        <I409> = 409;
        <I410> = 410;
        <I411> = 411;
        <I417> = 417;
        <I418> = 418;
        <I419> = 419;
        <I421> = 421;
        <I424> = 424;
        <I425> = 425;
        <I426> = 426;
        <I427> = 427;
        <I428> = 428;
        <I429> = 429;
        <I430> = 430;
        <I431> = 431;
        <I432> = 432;
        <I433> = 433;
        <I434> = 434;
        <I435> = 435;
        <I436> = 436;
        <I437> = 437;
        <I438> = 438;
        <I439> = 439;
        <I440> = 440;
        <I441> = 441;
        <I442> = 442;
        <I443> = 443;
        <I444> = 444;
        <I445> = 445;
        <I446> = 446;
        <I447> = 447;
        <I448> = 448;
        <I449> = 449;
        <I450> = 450;
        <I452> = 452;
        <I453> = 453;
        <I454> = 454;
        <I455> = 455;
        <I472> = 472;
        <I473> = 473;
        <I474> = 474;
        <I475> = 475;
        <I476> = 476;
        <I477> = 477;
        <I478> = 478;
        <I479> = 479;
        <I480> = 480;
        <I481> = 481;
        <I482> = 482;
        <I483> = 483;
        <I484> = 484;
        <I485> = 485;
        <I486> = 486;
        <I487> = 487;
        <I488> = 488;
        <I489> = 489;
        <I490> = 490;
        <I491> = 491;
        <I492> = 492;
        <I493> = 493;
        <I505> = 505;
        <I506> = 506;
        <I507> = 507;
        <I508> = 508;
        <I509> = 509;
        <I510> = 510;
        <I511> = 511;
        <I512> = 512;
        <I513> = 513;
        <I514> = 514;
        <I520> = 520;
        <I521> = 521;
        <I522> = 522;
        <I523> = 523;
        <I524> = 524;
        <I525> = 525;
        <I526> = 526;
        <I527> = 527;
        <I528> = 528;
        <I529> = 529;
        <I530> = 530;
        <I531> = 531;
        <I532> = 532;
        <I533> = 533;
        <I534> = 534;
        <I535> = 535;
        <I536> = 536;
        <I537> = 537;
        <I538> = 538;
        <I539> = 539;
        <I540> = 540;
        <I541> = 541;
        <I542> = 542;
        <I543> = 543;
        <I544> = 544;
        <I545> = 545;
        <I546> = 546;
        <I547> = 547;
        <I548> = 548;
        <I549> = 549;
        <I550> = 550;
        <I568> = 568;
        <I569> = 569;
        <I570> = 570;
        <I584> = 584;
        <I585> = 585;
        <I586> = 586;
        <I587> = 587;
        <I588> = 588;
        <I589> = 589;
        <I590> = 590;
        <I591> = 591;
        <I592> = 592;
        <I593> = 593;
        <I594> = 594;
        <I595> = 595;
        <I596> = 596;
        <I597> = 597;
        <I598> = 598;
        <I599> = 599;
        <I600> = 600;
        <I601> = 601;
        <I616> = 616;
        <I617> = 617;
        <I618> = 618;
        <I619> = 619;
        <I620> = 620;
        <I621> = 621;
        <I622> = 622;
        <I623> = 623;
        <I624> = 624;
        <I625> = 625;
        <I626> = 626;
        <I627> = 627;
        <I628> = 628;
        <I629> = 629;
        <I630> = 630;
        <I631> = 631;
        <I632> = 632;
        <I633> = 633;
        <I634> = 634;
        <I635> = 635;
        <I636> = 636;
        <I637> = 637;
        <I638> = 638;
        <I639> = 639;
        <I640> = 640;
        <I641> = 641;
        <I642> = 642;
        <I643> = 643;
        <I644> = 644;
        <I645> = 645;
        <I646> = 646;
        <I647> = 647;
        <I648> = 648;
        <I649> = 649;
        <I650> = 650;
        <I651> = 651;
        <I652> = 652;
        <I653> = 653;
        <I654> = 654;
        <I655> = 655;
        <I656> = 656;
        <I657> = 657;
        <I664> = 664;
        <I665> = 665;
        <I666> = 666;
        <I667> = 667;
        <I668> = 668;
        <I669> = 669;
        <I670> = 670;
        <I671> = 671;
        <I672> = 672;
        <I673> = 673;
        <I674> = 674;
        <I675> = 675;
        <I676> = 676;
        <I677> = 677;
        <I678> = 678;
        <I679> = 679;
        <I680> = 680;
        <I681> = 681;
        <I682> = 682;
        <I683> = 683;
        <I684> = 684;
        <I685> = 685;
        <I686> = 686;
        <I687> = 687;
        <I688> = 688;
        <I689> = 689;
        <I690> = 690;
        <I691> = 691;
        <I692> = 692;
        <I693> = 693;
        <I696> = 696;
        <I697> = 697;
        <I698> = 698;
        <I699> = 699;
        <I700> = 700;
        <I701> = 701;
        <I704> = 704;
        <I705> = 705;
        <I706> = 706;
        <I707> = 707;
        <I708> = 708;
        <I709> = 709;
        <INS> = 118;
        <KATA> = 98;
        <KP0> = 90;
        <KP1> = 87;
        <KP2> = 88;
        <KP3> = 89;
        <KP4> = 83;
        <KP5> = 84;
        <KP6> = 85;
        <KP7> = 79;
        <KP8> = 80;
        <KP9> = 81;
        <KPAD> = 86;
        <KPDL> = 91;
        <KPDV> = 106;
        <KPEN> = 104;
        <KPEQ> = 125;
        <KPMU> = 63;
        <KPSU> = 82;
        <LALT> = 64;
        <LCTL> = 37;
        <LEFT> = 113;
        <LFSH> = 50;
        <LNFD> = 109;
        <LSGT> = 94;
        <LVL3> = 92;
        <LVL5> = 203;
        <LWIN> = 133;
        <META> = 205;
        <MUHE> = 102;
        <MUTE> = 121;
        <NMLK> = 77;
        <OPEN> = 142;
        <PAST> = 143;
        <PAUS> = 127;
        <PGDN> = 117;
        <PGUP> = 112;
        <POWR> = 124;
        <PROP> = 138;
        <PRSC> = 107;
        <RALT> = 108;
        <RCTL> = 105;
        <RGHT> = 114;
        <RTRN> = 36;
        <RTSH> = 62;
        <RWIN> = 134;
        <SCLK> = 78;
        <SPCE> = 65;
        <STOP> = 136;
        <SUPR> = 206;
        <TAB> = 23;
        <TLDE> = 49;
        <UNDO> = 139;
        <UP> = 111;
        <VOL+> = 123;
        <VOL-> = 122;
        <ZEHA> = 93;
    };

    xkb_types {
        virtual_modifiers Alt = Mod1;
        virtual_modifiers Hyper;
        virtual_modifiers LevelFive = Mod3;
        virtual_modifiers LevelThree = Mod5;
        virtual_modifiers Meta = Mod1;
        virtual_modifiers NumLock = Mod2;
        virtual_modifiers ScrollLock;
        virtual_modifiers Super = Mod4;

        type "ALPHABETIC" {
            modifiers = Shift+Lock;
            level_name[Level1] = "Base";
            level_name[Level2] = "Caps";
            map[Shift] = Level2;
            map[Lock] = Level2;
        };

        type "CTRL+ALT" {
            modifiers = Shift+Control+Mod1+Mod5;
            level_name[Level1] = "Base";
            level_name[Level2] = "Shift";
            level_name[Level3] = "AltGr";
            level_name[Level4] = "Shift AltGr";
            level_name[Level5] = "Ctrl+Alt";
            map[None] = Level1;
            map[Control] = Level1;
            preserve[Control] = Control;
            map[Mod1] = Level1;
            preserve[Mod1] = Mod1;
            map[Shift] = Level2;
            preserve[Shift] = Shift;
            map[Shift+Control] = Level2;
            preserve[Shift+Control] = Shift+Control;
            map[Shift+Mod1] = Level2;
            preserve[Shift+Mod1] = Shift+Mod1;
            map[Shift+Control+Mod1] = Level2;
            preserve[Shift+Control+Mod1] = Shift+Control+Mod1;
            map[Mod5] = Level3;
            map[Control+Mod5] = Level3;
            preserve[Control+Mod5] = Control;
            map[Mod1+Mod5] = Level3;
            preserve[Mod1+Mod5] = Mod1;
            map[Control+Mod1+Mod5] = Level3;
            preserve[Control+Mod1+Mod5] = Control+Mod1;
            map[Shift+Mod5] = Level4;
            preserve[Shift+Mod5] = Shift;
            map[Shift+Control+Mod5] = Level4;
            preserve[Shift+Control+Mod5] = Shift+Control;
            map[Shift+Mod1+Mod5] = Level4;
            preserve[Shift+Mod1+Mod5] = Shift+Mod1;
            map[Shift+Control+Mod1+Mod5] = Level4;
            preserve[Shift+Control+Mod1+Mod5] = Shift+Control+Mod1;
            map[Control+Mod1] = Level5;
        };

        type "FOUR_LEVEL" {
            modifiers = Shift+Mod5;
            level_name[Level1] = "Base";
            level_name[Level2] = "Shift";
            level_name[Level3] = "AltGr";
            level_name[Level4] = "Shift AltGr";
            map[None] = Level1;
            map[Shift] = Level2;
            map[Mod5] = Level3;
            map[Shift+Mod5] = Level4;
        };

        type "KEYPAD" {
            modifiers = Shift+Mod2;
            level_name[Level1] = "Base";
            level_name[Level2] = "Number";
            map[None] = Level1;
            map[Shift+Mod2] = Level1;
            map[Mod2] = Level2;
        };

        type "ONE_LEVEL" {
            modifiers = None;
            level_name[Level1] = "Any";
            map[None] = Level1;
        };

        type "PC_ALT_LEVEL2" {
            modifiers = Mod1;
            level_name[Level1] = "Base";
            level_name[Level2] = "Alt";
            map[None] = Level1;
            map[Mod1] = Level2;
        };

        type "PC_CONTROL_LEVEL2" {
            modifiers = Control;
            level_name[Level1] = "Base";
            level_name[Level2] = "Control";
            map[None] = Level1;
            map[Control] = Level2;
        };

        type "PC_CONTROL_SUPER_LEVEL2" {
            modifiers = Control+Mod4;
            level_name[Level1] = "Base";
            level_name[Level2] = "Control + Super";
            map[None] = Level1;
            map[Control] = Level1;
            preserve[Control] = Control;
            map[Mod4] = Level1;
            preserve[Mod4] = Mod4;
            map[Control+Mod4] = Level2;
        };

        type "PC_SHIFT_SUPER_LEVEL2" {
            modifiers = Shift+Mod4;
            level_name[Level1] = "Base";
            level_name[Level2] = "Super";
            map[None] = Level1;
            map[Shift+Mod4] = Level2;
        };

        type "TWO_LEVEL" {
            modifiers = Shift;
            level_name[Level1] = "Base";
            level_name[Level2] = "Shift";
            map[Shift] = Level2;
        };
    };

    xkb_compat {
        indicator "Caps Lock" {
            modifiers = Lock;
            whichModState = Locked;
        };
        indicator "Num Lock" {
            modifiers = Mod2;
            whichModState = Locked;
        };
        indicator "Shift Lock" {
            modifiers = Shift;
            whichModState = Locked;
        };
        indicator "Group 2" {
            groups = 0xfffffffe;
        };
        indicator "Mouse Keys" {
            controls = MouseKeys;
        };

        interpret VoidSymbol {
            repeat = false;
        };
    };

    xkb_symbols {
        modmap Shift { <LFSH> };
        modmap Shift { <RTSH> };
        modmap Lock { <CAPS> };
        modmap Control { <LCTL> };
        modmap Control { <RCTL> };
        modmap Mod1 { <ALT> };
        modmap Mod1 { <LALT> };
        modmap Mod1 { <META> };
        modmap Mod1 { Meta_L }; // <META>
        modmap Mod1 { <RALT> };
        modmap Mod2 { <NMLK> };
        modmap Mod3 { <LVL5> };
        modmap Mod4 { <LWIN> };
        modmap Mod4 { <RWIN> };
        modmap Mod4 { <SUPR> };
        modmap Mod5 { <LVL3> };

        name[Group1] = "English (US)";

        key.repeat = true;

        key <AB01> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ z, Z ]
        };
        key <AB02> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ x, X ]
        };
        key <AB03> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ c, C ]
        };
        key <AB04> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ v, V ]
        };
        key <AB05> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ b, B ]
        };
        key <AB06> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ n, N ]
        };
        key <AB07> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ m, M ]
        };
        key <AB08> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ comma, less ]
        };
        key <AB09> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ period, greater ]
        };
        key <AB10> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ slash, question ]
        };
        key <AC01> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ a, A ]
        };
        key <AC02> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ s, S ]
        };
        key <AC03> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ d, D ]
        };
        key <AC04> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ f, F ]
        };
        key <AC05> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ g, G ]
        };
        key <AC06> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ h, H ]
        };
        key <AC07> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ j, J ]
        };
        key <AC08> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ k, K ]
        };
        key <AC09> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ l, L ]
        };
        key <AC10> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ semicolon, colon ]
        };
        key <AC11> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ apostrophe, quotedbl ]
        };
        key <AD01> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ q, Q ]
        };
        key <AD02> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ w, W ]
        };
        key <AD03> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ e, E ]
        };
        key <AD04> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ r, R ]
        };
        key <AD05> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ t, T ]
        };
        key <AD06> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ y, Y ]
        };
        key <AD07> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ u, U ]
        };
        key <AD08> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ i, I ]
        };
        key <AD09> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ o, O ]
        };
        key <AD10> {
            type[Group1] = "ALPHABETIC",
            symbols[Group1] = [ p, P ]
        };
        key <AD11> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ bracketleft, braceleft ]
        };
        key <AD12> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ bracketright, braceright ]
        };
        key <AE01> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 1, exclam ]
        };
        key <AE02> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 2, at ]
        };
        key <AE03> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 3, numbersign ]
        };
        key <AE04> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 4, dollar ]
        };
        key <AE05> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 5, percent ]
        };
        key <AE06> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 6, asciicircum ]
        };
        key <AE07> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 7, ampersand ]
        };
        key <AE08> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 8, asterisk ]
        };
        key <AE09> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 9, parenleft ]
        };
        key <AE10> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ 0, parenright ]
        };
        key <AE11> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ minus, underscore ]
        };
        key <AE12> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ equal, plus ]
        };
        key <AGAI> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Redo ]
        };
        key <ALT> {
            repeat = false,
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ NoSymbol, Alt_L ],
            actions[Group1] = [ NoAction(), SetMods(modifiers = Mod1, clearLocks) ]
        };
        key <BKSL> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ backslash, bar ]
        };
        key <BKSP> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ BackSpace, BackSpace ]
        };
        key <CAPS> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Caps_Lock ],
            actions[Group1] = [ LockMods(modifiers = Lock) ]
        };
        key <COMP> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Menu ]
        };
        key <COPY> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Copy ]
        };
        key <CUT> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Cut ]
        };
        key <DELE> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Delete ]
        };
        key <DOWN> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Down ]
        };
        key <END> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ End ]
        };
        key <ESC> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Escape ]
        };
        key <FIND> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Find ]
        };
        key <FK01> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F1, F1, F1, F1, XF86Switch_VT_1 ]
        };
        key <FK02> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F2, F2, F2, F2, XF86Switch_VT_2 ]
        };
        key <FK03> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F3, F3, F3, F3, XF86Switch_VT_3 ]
        };
        key <FK04> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F4, F4, F4, F4, XF86Switch_VT_4 ]
        };
        key <FK05> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F5, F5, F5, F5, XF86Switch_VT_5 ]
        };
        key <FK06> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F6, F6, F6, F6, XF86Switch_VT_6 ]
        };
        key <FK07> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F7, F7, F7, F7, XF86Switch_VT_7 ]
        };
        key <FK08> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F8, F8, F8, F8, XF86Switch_VT_8 ]
        };
        key <FK09> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F9, F9, F9, F9, XF86Switch_VT_9 ]
        };
        key <FK10> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F10, F10, F10, F10, XF86Switch_VT_10 ]
        };
        key <FK11> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F11, F11, F11, F11, XF86Switch_VT_11 ]
        };
        key <FK12> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ F12, F12, F12, F12, XF86Switch_VT_12 ]
        };
        key <FK13> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Tools ]
        };
        key <FK14> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch5 ]
        };
        key <FK15> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch6 ]
        };
        key <FK16> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch7 ]
        };
        key <FK17> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch8 ]
        };
        key <FK18> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch9 ]
        };
        key <FK19> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ F19 ]
        };
        key <FK20> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioMicMute ]
        };
        key <FK21> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TouchpadToggle ]
        };
        key <FK22> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TouchpadOn ]
        };
        key <FK23> {
            type[Group1] = "PC_SHIFT_SUPER_LEVEL2",
            symbols[Group1] = [ F23, XF86Assistant ]
        };
        key <FK24> {
            type[Group1] = "PC_CONTROL_SUPER_LEVEL2",
            symbols[Group1] = [ F24, XF86TouchpadToggle ]
        };
        key <FRNT> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ SunFront ]
        };
        key <HELP> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Help ]
        };
        key <HENK> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Henkan_Mode ]
        };
        key <HIRA> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Hiragana ]
        };
        key <HJCV> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Hangul_Hanja ]
        };
        key <HKTG> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Hiragana_Katakana ]
        };
        key <HNGL> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Hangul ]
        };
        key <HOME> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Home ]
        };
        key <HYPR> {
            repeat = false,
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ NoSymbol, Hyper_L ]
        };
        key <I126> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ plusminus ]
        };
        key <I128> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LaunchA ]
        };
        key <I129> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Decimal, KP_Decimal ]
        };
        key <I147> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MenuKB ]
        };
        key <I148> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Calculator ]
        };
        key <I150> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Sleep ]
        };
        key <I151> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86WakeUp ]
        };
        key <I152> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Explorer ]
        };
        key <I153> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Send ]
        };
        key <I155> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Xfer ]
        };
        key <I156> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch1 ]
        };
        key <I157> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch2 ]
        };
        key <I158> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86WWW ]
        };
        key <I159> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86DOS ]
        };
        key <I160> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ScreenSaver ]
        };
        key <I161> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RotateWindows ]
        };
        key <I162> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TaskPane ]
        };
        key <I163> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Mail ]
        };
        key <I164> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Favorites ]
        };
        key <I165> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MyComputer ]
        };
        key <I166> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Back ]
        };
        key <I167> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Forward ]
        };
        key <I169> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Eject ]
        };
        key <I170> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Eject ]
        };
        key <I171> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioNext ]
        };
        key <I172> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ XF86AudioPlay, XF86AudioPause ]
        };
        key <I173> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioPrev ]
        };
        key <I174> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ XF86AudioStop, XF86Eject ]
        };
        key <I175> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioRecord ]
        };
        key <I176> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioRewind ]
        };
        key <I177> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Phone ]
        };
        key <I179> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Tools ]
        };
        key <I180> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86HomePage ]
        };
        key <I181> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Reload ]
        };
        key <I182> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Close ]
        };
        key <I185> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ScrollUp ]
        };
        key <I186> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ScrollDown ]
        };
        key <I187> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ parenleft ]
        };
        key <I188> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ parenright ]
        };
        key <I189> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86New ]
        };
        key <I190> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Redo ]
        };
        key <I208> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioPlay ]
        };
        key <I209> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioPause ]
        };
        key <I210> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch3 ]
        };
        key <I211> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Launch4 ]
        };
        key <I212> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LaunchB ]
        };
        key <I213> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Suspend ]
        };
        key <I214> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Close ]
        };
        key <I215> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioPlay ]
        };
        key <I216> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioForward ]
        };
        key <I217> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioBassBoost ]
        };
        key <I218> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Print ]
        };
        key <I220> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86WebCam ]
        };
        key <I221> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioPreset ]
        };
        key <I223> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Mail ]
        };
        key <I224> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Messenger ]
        };
        key <I225> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Search ]
        };
        key <I226> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Go ]
        };
        key <I227> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Finance ]
        };
        key <I228> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Game ]
        };
        key <I229> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Shop ]
        };
        key <I231> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Cancel ]
        };
        key <I232> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MonBrightnessDown ]
        };
        key <I233> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MonBrightnessUp ]
        };
        key <I234> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioMedia ]
        };
        key <I235> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Display ]
        };
        key <I236> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdLightOnOff ]
        };
        key <I237> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdBrightnessDown ]
        };
        key <I238> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdBrightnessUp ]
        };
        key <I239> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Send ]
        };
        key <I240> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Reply ]
        };
        key <I241> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MailForward ]
        };
        key <I242> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Save ]
        };
        key <I243> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Documents ]
        };
        key <I244> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Battery ]
        };
        key <I245> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Bluetooth ]
        };
        key <I246> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86WLAN ]
        };
        key <I247> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86UWB ]
        };
        key <I248> {
            repeat = false
        };
        key <I249> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Next_VMode ]
        };
        key <I250> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Prev_VMode ]
        };
        key <I251> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MonBrightnessCycle ]
        };
        key <I252> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86BrightnessAuto ]
        };
        key <I253> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86DisplayOff ]
        };
        key <I254> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86WWAN ]
        };
        key <I255> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RFKill ]
        };
        key <I256> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioMicMute ]
        };
        key <I360> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86OK ]
        };
        key <I361> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Select ]
        };
        key <I362> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86GoTo ]
        };
        key <I363> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Clear ]
        };
        key <I365> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Option ]
        };
        key <I366> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Info ]
        };
        key <I367> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Time ]
        };
        key <I368> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86VendorLogo ]
        };
        key <I370> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectProgramGuide ]
        };
        key <I371> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NextFavorite ]
        };
        key <I372> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Favorites ]
        };
        key <I373> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectProgramGuide ]
        };
        key <I374> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectHome ]
        };
        key <I376> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaLanguageMenu ]
        };
        key <I377> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaTitleMenu ]
        };
        key <I378> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Subtitle ]
        };
        key <I379> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CycleAngle ]
        };
        key <I380> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86FullScreen ]
        };
        key <I381> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioChannelMode ]
        };
        key <I382> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Keyboard ]
        };
        key <I383> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AspectRatio ]
        };
        key <I384> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectPC ]
        };
        key <I385> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectTV ]
        };
        key <I386> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectCable ]
        };
        key <I387> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectVCR ]
        };
        key <I388> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectVCRPlus ]
        };
        key <I389> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectSatellite ]
        };
        key <I391> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CD ]
        };
        key <I392> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectTape ]
        };
        key <I393> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectRadio ]
        };
        key <I394> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectTuner ]
        };
        key <I395> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaPlayer ]
        };
        key <I396> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectTeletext ]
        };
        key <I397> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86DVD ]
        };
        key <I398> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaSelectAuxiliary ]
        };
        key <I400> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Audio ]
        };
        key <I401> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Video ]
        };
        key <I404> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Memo ]
        };
        key <I405> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Calendar ]
        };
        key <I406> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Red ]
        };
        key <I407> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Green ]
        };
        key <I408> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Yellow ]
        };
        key <I409> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Blue ]
        };
        key <I410> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ChannelUp ]
        };
        key <I411> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ChannelDown ]
        };
        key <I417> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaPlaySlow ]
        };
        key <I418> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioRandomPlay ]
        };
        key <I419> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Break ]
        };
        key <I421> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumberEntryMode ]
        };
        key <I424> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86VideoPhone ]
        };
        key <I425> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Game ]
        };
        key <I426> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ZoomIn ]
        };
        key <I427> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ZoomOut ]
        };
        key <I428> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ZoomReset ]
        };
        key <I429> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Word ]
        };
        key <I430> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Editor ]
        };
        key <I431> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Excel ]
        };
        key <I432> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86GraphicsEditor ]
        };
        key <I433> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Presentation ]
        };
        key <I434> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Database ]
        };
        key <I435> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86News ]
        };
        key <I436> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Voicemail ]
        };
        key <I437> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Addressbook ]
        };
        key <I438> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Messenger ]
        };
        key <I439> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86DisplayToggle ]
        };
        key <I440> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86SpellCheck ]
        };
        key <I441> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LogOff ]
        };
        key <I442> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ dollar ]
        };
        key <I443> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ EuroSign ]
        };
        key <I444> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86FrameBack ]
        };
        key <I445> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86FrameForward ]
        };
        key <I446> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ContextMenu ]
        };
        key <I447> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaRepeat ]
        };
        key <I448> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF8610ChannelsUp ]
        };
        key <I449> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF8610ChannelsDown ]
        };
        key <I450> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Images ]
        };
        key <I452> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NotificationCenter ]
        };
        key <I453> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86PickupPhone ]
        };
        key <I454> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86HangupPhone ]
        };
        key <I455> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LinkPhone ]
        };
        key <I472> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn ]
        };
        key <I473> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_Esc ]
        };
        key <I474> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F1 ]
        };
        key <I475> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F2 ]
        };
        key <I476> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F3 ]
        };
        key <I477> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F4 ]
        };
        key <I478> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F5 ]
        };
        key <I479> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F6 ]
        };
        key <I480> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F7 ]
        };
        key <I481> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F8 ]
        };
        key <I482> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F9 ]
        };
        key <I483> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F10 ]
        };
        key <I484> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F11 ]
        };
        key <I485> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F12 ]
        };
        key <I486> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_1 ]
        };
        key <I487> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_2 ]
        };
        key <I488> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_D ]
        };
        key <I489> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_E ]
        };
        key <I490> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_F ]
        };
        key <I491> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_S ]
        };
        key <I492> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Fn_B ]
        };
        key <I493> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86FnRightShift ]
        };
        key <I505> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_1 ]
        };
        key <I506> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_2 ]
        };
        key <I507> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_3 ]
        };
        key <I508> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_4 ]
        };
        key <I509> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_5 ]
        };
        key <I510> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_6 ]
        };
        key <I511> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_7 ]
        };
        key <I512> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_8 ]
        };
        key <I513> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_9 ]
        };
        key <I514> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ braille_dot_1 ]
        };
        key <I520> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric0 ]
        };
        key <I521> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric1 ]
        };
        key <I522> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric2 ]
        };
        key <I523> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric3 ]
        };
        key <I524> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric4 ]
        };
        key <I525> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric5 ]
        };
        key <I526> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric6 ]
        };
        key <I527> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric7 ]
        };
        key <I528> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric8 ]
        };
        key <I529> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric9 ]
        };
        key <I530> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumericStar ]
        };
        key <I531> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumericPound ]
        };
        key <I532> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumericA ]
        };
        key <I533> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumericB ]
        };
        key <I534> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumericC ]
        };
        key <I535> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NumericD ]
        };
        key <I536> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraFocus ]
        };
        key <I537> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86WPSButton ]
        };
        key <I538> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TouchpadToggle ]
        };
        key <I539> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TouchpadOn ]
        };
        key <I540> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TouchpadOff ]
        };
        key <I541> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraZoomIn ]
        };
        key <I542> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraZoomOut ]
        };
        key <I543> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraUp ]
        };
        key <I544> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraDown ]
        };
        key <I545> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraLeft ]
        };
        key <I546> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraRight ]
        };
        key <I547> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AttendantOn ]
        };
        key <I548> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AttendantOff ]
        };
        key <I549> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AttendantToggle ]
        };
        key <I550> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LightsToggle ]
        };
        key <I568> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ALSToggle ]
        };
        key <I569> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RotationLockToggle ]
        };
        key <I570> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RefreshRateToggle ]
        };
        key <I584> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Buttonconfig ]
        };
        key <I585> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Taskmanager ]
        };
        key <I586> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Journal ]
        };
        key <I587> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ControlPanel ]
        };
        key <I588> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AppSelect ]
        };
        key <I589> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Screensaver ]
        };
        key <I590> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86VoiceCommand ]
        };
        key <I591> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Assistant ]
        };
        key <I592> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ ISO_Next_Group ],
            actions[Group1] = [ LockGroup(group = +1) ]
        };
        key <I593> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86EmojiPicker ]
        };
        key <I594> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Dictate ]
        };
        key <I595> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraAccessEnable ]
        };
        key <I596> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraAccessDisable ]
        };
        key <I597> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86CameraAccessToggle ]
        };
        key <I598> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Accessibility ]
        };
        key <I599> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86DoNotDisturb ]
        };
        key <I600> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86BrightnessMin ]
        };
        key <I601> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86BrightnessMax ]
        };
        key <I616> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdInputAssistPrev ]
        };
        key <I617> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdInputAssistNext ]
        };
        key <I618> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdInputAssistPrevgroup ]
        };
        key <I619> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdInputAssistNextgroup ]
        };
        key <I620> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdInputAssistAccept ]
        };
        key <I621> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdInputAssistCancel ]
        };
        key <I622> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RightUp ]
        };
        key <I623> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RightDown ]
        };
        key <I624> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LeftUp ]
        };
        key <I625> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86LeftDown ]
        };
        key <I626> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RootMenu ]
        };
        key <I627> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MediaTopMenu ]
        };
        key <I628> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric11 ]
        };
        key <I629> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Numeric12 ]
        };
        key <I630> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioDesc ]
        };
        key <I631> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF863DMode ]
        };
        key <I632> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NextFavorite ]
        };
        key <I633> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86StopRecord ]
        };
        key <I634> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86PauseRecord ]
        };
        key <I635> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86VOD ]
        };
        key <I636> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Unmute ]
        };
        key <I637> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86FastReverse ]
        };
        key <I638> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86SlowReverse ]
        };
        key <I639> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Data ]
        };
        key <I640> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86OnScreenKeyboard ]
        };
        key <I641> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86PrivacyScreenToggle ]
        };
        key <I642> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86SelectiveScreenshot ]
        };
        key <I643> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NextElement ]
        };
        key <I644> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86PreviousElement ]
        };
        key <I645> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AutopilotEngageToggle ]
        };
        key <I646> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MarkWaypoint ]
        };
        key <I647> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Sos ]
        };
        key <I648> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NavChart ]
        };
        key <I649> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86FishingChart ]
        };
        key <I650> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86SingleRangeRadar ]
        };
        key <I651> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86DualRangeRadar ]
        };
        key <I652> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86RadarOverlay ]
        };
        key <I653> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86TraditionalSonar ]
        };
        key <I654> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86ClearvuSonar ]
        };
        key <I655> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86SidevuSonar ]
        };
        key <I656> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86NavInfo ]
        };
        key <I657> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86BrightnessAdjust ]
        };
        key <I664> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro1 ]
        };
        key <I665> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro2 ]
        };
        key <I666> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro3 ]
        };
        key <I667> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro4 ]
        };
        key <I668> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro5 ]
        };
        key <I669> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro6 ]
        };
        key <I670> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro7 ]
        };
        key <I671> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro8 ]
        };
        key <I672> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro9 ]
        };
        key <I673> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro10 ]
        };
        key <I674> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro11 ]
        };
        key <I675> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro12 ]
        };
        key <I676> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro13 ]
        };
        key <I677> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro14 ]
        };
        key <I678> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro15 ]
        };
        key <I679> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro16 ]
        };
        key <I680> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro17 ]
        };
        key <I681> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro18 ]
        };
        key <I682> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro19 ]
        };
        key <I683> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro20 ]
        };
        key <I684> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro21 ]
        };
        key <I685> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro22 ]
        };
        key <I686> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro23 ]
        };
        key <I687> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro24 ]
        };
        key <I688> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro25 ]
        };
        key <I689> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro26 ]
        };
        key <I690> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro27 ]
        };
        key <I691> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro28 ]
        };
        key <I692> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro29 ]
        };
        key <I693> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Macro30 ]
        };
        key <I696> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MacroRecordStart ]
        };
        key <I697> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MacroRecordStop ]
        };
        key <I698> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MacroPresetCycle ]
        };
        key <I699> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MacroPreset1 ]
        };
        key <I700> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MacroPreset2 ]
        };
        key <I701> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86MacroPreset3 ]
        };
        key <I704> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdLcdMenu1 ]
        };
        key <I705> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdLcdMenu2 ]
        };
        key <I706> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdLcdMenu3 ]
        };
        key <I707> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdLcdMenu4 ]
        };
        key <I708> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86KbdLcdMenu5 ]
        };
        key <I709> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86PerformanceMode ]
        };
        key <INS> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Insert ]
        };
        key <KATA> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Katakana ]
        };
        key <KP0> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Insert, KP_0 ]
        };
        key <KP1> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_End, KP_1 ]
        };
        key <KP2> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Down, KP_2 ]
        };
        key <KP3> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Next, KP_3 ]
        };
        key <KP4> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Left, KP_4 ]
        };
        key <KP5> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Begin, KP_5 ]
        };
        key <KP6> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Right, KP_6 ]
        };
        key <KP7> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Home, KP_7 ]
        };
        key <KP8> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Up, KP_8 ]
        };
        key <KP9> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Prior, KP_9 ]
        };
        key <KPAD> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ KP_Add, KP_Add, KP_Add, KP_Add, XF86Next_VMode ]
        };
        key <KPDL> {
            type[Group1] = "KEYPAD",
            symbols[Group1] = [ KP_Delete, KP_Decimal ]
        };
        key <KPDV> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ KP_Divide, KP_Divide, KP_Divide, KP_Divide, XF86Ungrab ]
        };
        key <KPEN> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ KP_Enter ]
        };
        key <KPEQ> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ KP_Equal ]
        };
        key <KPMU> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ KP_Multiply, KP_Multiply, KP_Multiply, KP_Multiply, XF86ClearGrab ]
        };
        key <KPSU> {
            type[Group1] = "CTRL+ALT",
            symbols[Group1] = [ KP_Subtract, KP_Subtract, KP_Subtract, KP_Subtract, XF86Prev_VMode ]
        };
        key <LALT> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Alt_L ],
            actions[Group1] = [ SetMods(modifiers = Mod1, clearLocks) ]
        };
        key <LCTL> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Control_L ],
            actions[Group1] = [ SetMods(modifiers = Control, clearLocks) ]
        };
        key <LEFT> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Left ]
        };
        key <LFSH> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Shift_L ],
            actions[Group1] = [ SetMods(modifiers = Shift, clearLocks) ]
        };
        key <LNFD> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Linefeed ]
        };
        key <LSGT> {
            type[Group1] = "FOUR_LEVEL",
            symbols[Group1] = [ less, greater, bar, brokenbar ]
        };
        key <LVL3> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ ISO_Level3_Shift ],
            actions[Group1] = [ SetMods(modifiers = Mod5, clearLocks) ]
        };
        key <LVL5> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ ISO_Level5_Shift ],
            actions[Group1] = [ SetMods(modifiers = Mod3, clearLocks) ]
        };
        key <LWIN> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Super_L ],
            actions[Group1] = [ SetMods(modifiers = Mod4, clearLocks) ]
        };
        key <META> {
            repeat = false,
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ NoSymbol, Meta_L ],
            actions[Group1] = [ NoAction(), SetMods(modifiers = Mod1, clearLocks) ]
        };
        key <MUHE> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Muhenkan ]
        };
        key <MUTE> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioMute ]
        };
        key <NMLK> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Num_Lock ],
            actions[Group1] = [ LockMods(modifiers = Mod2) ]
        };
        key <OPEN> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Open ]
        };
        key <PAST> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86Paste ]
        };
        key <PAUS> {
            type[Group1] = "PC_CONTROL_LEVEL2",
            symbols[Group1] = [ Pause, Break ]
        };
        key <PGDN> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Next ]
        };
        key <PGUP> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Prior ]
        };
        key <POWR> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86PowerOff ]
        };
        key <PROP> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ SunProps ]
        };
        key <PRSC> {
            type[Group1] = "PC_ALT_LEVEL2",
            symbols[Group1] = [ Print, Sys_Req ]
        };
        key <RALT> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Alt_R ],
            actions[Group1] = [ SetMods(modifiers = Mod1, clearLocks) ]
        };
        key <RCTL> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Control_R ],
            actions[Group1] = [ SetMods(modifiers = Control, clearLocks) ]
        };
        key <RGHT> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Right ]
        };
        key <RTRN> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Return ]
        };
        key <RTSH> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Shift_R ],
            actions[Group1] = [ SetMods(modifiers = Shift, clearLocks) ]
        };
        key <RWIN> {
            repeat = false,
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Super_R ],
            actions[Group1] = [ SetMods(modifiers = Mod4, clearLocks) ]
        };
        key <SCLK> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Scroll_Lock ]
        };
        key <SPCE> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ space ]
        };
        key <STOP> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Cancel ]
        };
        key <SUPR> {
            repeat = false,
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ NoSymbol, Super_L ],
            actions[Group1] = [ NoAction(), SetMods(modifiers = Mod4, clearLocks) ]
        };
        key <TAB> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ Tab, ISO_Left_Tab ]
        };
        key <TLDE> {
            type[Group1] = "TWO_LEVEL",
            symbols[Group1] = [ grave, asciitilde ]
        };
        key <UNDO> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Undo ]
        };
        key <UP> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ Up ]
        };
        key <VOL+> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioRaiseVolume ]
        };
        key <VOL-> {
            type[Group1] = "ONE_LEVEL",
            symbols[Group1] = [ XF86AudioLowerVolume ]
        };
        key <ZEHA> {
            type[Group1] = "PC_CONTROL_SUPER_LEVEL2",
            symbols[Group1] = [ F24, XF86TouchpadToggle ]
        };
    };
};"#;

#[cfg(test)]
mod tests {
    use sha2::{Digest, Sha256};

    // pins tools/gen-keymap/src/main.rs as of the last regeneration
    const GEN_SRC_HASH: &str = "9be9d06cc7b4bc7b31bb23f5951c9aea0e3924c346217e15196fedb5c2177a15";
    const MAP_HASH: &str = "0fe73f19fa0d6f3db3ff224a744543b25caf18e00ffb608f9a1bd9e8bbc350cd";
    const REGEN: &str =
        "default keymap out of date - rerun: cargo run --manifest-path tools/gen-keymap/Cargo.toml";

    fn hex(b: &[u8]) -> String {
        b.iter().map(|x| format!("{x:02x}")).collect()
    }

    #[test]
    fn generator_matches_committed_text() {
        let gen_src = include_str!("../../tools/gen-keymap/src/main.rs");
        assert_eq!(GEN_SRC_HASH, hex(&Sha256::digest(gen_src.as_bytes())), "{REGEN}");
        assert_eq!(MAP_HASH, hex(&Sha256::digest(super::DEFAULT_KEYMAP.as_bytes())), "{REGEN}");
    }
}
